# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-27 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210727_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='username',
            new_name='user',
        ),
    ]
